kernel_name = "python3"
language_name = "python"

code_hello_world = "print('hello, world')"

complete_code_samples = [
    "1",
    "print('hello, world')",
    "def f(x):\n  return x*2\n\n"
]

incomplete_code_samples = [
    "print('''hello",
    "def f(x):\n  x*2"
]

code_page_something = "zip?"
code_generate_error = "raise"

[[completion_samples]]
text = "zi"
matches = ["zip"]

[[code_execute_result]]
code = "1+1"
result = "2"

[[code_display_data]]
code = "from IPython.display import HTML, display; display(HTML('<b>test</b>'))"
mime = "text/html"
[[code_display_data]]
code = "from IPython.display import Math, display; display(Math('\\frac{1}{2}'))"
mime = "text/latex"
